### DISCUSSION TITLE
Support for non-OAS linting

### DISCUSSION THREAD

**Discussion by rspurgeon** [daveshanley/vacuum#280] [Ideas]
Vacuum looks superb, and a great fit for a project I have in mind. Thanks to everyone for building such an interesting public project. 

My project looks to build general YAML file based linting.  As vacuum is OAS opinionated, I believe I'm blocked from creating non-OAS based rules and passing the library non-OAS data.  I'm wondering if anyone here has thoughts on how this might be possible, or workarounds in the current codebase?  I really appreciate any attention to this discussion.  Thanks

**Comment by daveshanley** [comment]
Hi, 

You could use the core functions for building your own rules for sure. There is nothing about the core functionality tied to OpenAPI, they will work with any valid JSON path. So you could quickly build a non-OAS set of rules for any generic YAML file.

To see the available core functions:

https://quobix.com/vacuum/functions/core/

None of the OpenAPI functions will be helpful in a non-OpenAPI document, and you would also have to turn off all the rules and build using just your custom ones.

While it's not the purpose of vacuum, there is nothing stopping you from using it as a generic linter.

**Reply by mheap** [reply]
Do you have any pointers to get started? Here's what I've tried so far:

`summertime.yaml`:

```yaml
_format_version: "3.0"
services:
- host: mockbin.org
  id: b1525aee-d304-11ed-afa1-0242ac120002
  name: summer-time
  path: /requests
  plugins: []
  port: 443
  protocol: https
  routes:
  - id: b7d87736-d304-11ed-afa1-0242ac120002
    methods:
    - GET
    name: summer-time_get
    paths:
    - ~/summer-time$
    plugins: []
    regex_priority: 200
    strip_path: false
    tags: []
```

`custom-ruleset.yaml`:

```yaml
rules:
  my-new-rule:
    description: "Check the version is correct"
    given: $._format_version
    severity: error
    then:
      function: pattern
      functionOptions:
        match: "^1.1$"
```

Running with the CLI errors with a `libopenapi` error:

```
❯ vacuum lint -r custom-ruleset.yaml ./summertime.yaml

██    ██  █████   ██████ ██    ██ ██    ██ ███    ███
██    ██ ██   ██ ██      ██    ██ ██    ██ ████  ████
██    ██ ███████ ██      ██    ██ ██    ██ ██ ████ ██
 ██  ██  ██   ██ ██      ██    ██ ██    ██ ██  ██  ██
  ████   ██   ██  ██████  ██████   ██████  ██      ██

version: 0.2.6 | compiled: 2023-07-21T15:58:18Z
🔗 https://quobix.com/vacuum | https://github.com/daveshanley/vacuum


 INFO  Linting against 1 rules:
  ERROR   linting error: spec type not supported by libopenapi, sorry
```

And if I try to run the ruleset programatically without extending the default set I get a similar error:

```golang
package main

import (
	"fmt"
	"io/ioutil"

	"github.com/daveshanley/vacuum/motor"
	"github.com/daveshanley/vacuum/rulesets"
)

func main() {

	// read in a RuleSet file
	ruleSetBytes, err := ioutil.ReadFile("custom-ruleset.yaml")
	if err != nil {
		panic(err.Error())
	}

	// extract a custom RuleSet from our bytes.
	customRuleSet, rsErr := rulesets.CreateRuleSetFromData(ruleSetBytes)

	if rsErr != nil {
		panic(err.Error())
	}

	// read in an OpenAPI specification
	specBytes, err := ioutil.ReadFile("summertime.yaml")
	if err != nil {
		panic(err.Error())
	}

	// apply custom ruleset to our specification
	ruleSetResults := motor.ApplyRulesToRuleSet(&motor.RuleSetExecution{
		RuleSet: customRuleSet,
		Spec:    specBytes,
	})

	if len(ruleSetResults.Errors) > 0 {
		fmt.Printf("Errors: %v\n\n", ruleSetResults.Errors)
		return
	}

	// print out how many violations were found.
	fmt.Printf("Linting Violations: %d", len(ruleSetResults.Results))

	// iterate over each violation of this rule
	for _, violation := range ruleSetResults.Results {

		// print out the start line, column, violation message.
		fmt.Printf(" - [%d:%d] %s\n", violation.StartNode.Line,
			violation.StartNode.Column, violation.Message)
	}
}
```

Returns:

```
Errors: [spec type not supported by libopenapi, sorry]
```
