### DISCUSSION TITLE
How to conditionally turn-off a rule

### DISCUSSION THREAD

**Discussion by avin3sh** [daveshanley/vacuum#467] [Q&A]
I have a hypothetical scenario where for some reason a particular component in my spec fails `component-description` rule. I have an option to just specify `component-description: off` in my RuleSet - however I want to make an exception for this particular schema component and have rule working for rest of the spec.

How do I go about this ? If I could specify an expression in the `given` override for the rule, it would made it easy but I will admit I do not fully understand how JSONPath is being used.

Is there a moral equivalent of `given: $ but not $.components.schemas['BadComponent']`

If the above was possible, I could easily make an exception in my RuleSet like this:
```YAML
extends: [[spectral:oas, recommended]]
rules:
  component-description:
    given: $ but not $.components.schemas['BadComponent']
    then:
      function: oasComponentDescriptions # Probably this is not even needed
```
