### DISCUSSION TITLE
How do i configure the rules for examples, to prevent duplicate examples

### DISCUSSION THREAD

**Discussion by Samuel-Morgan-Tyghe** [daveshanley/vacuum#539] [Q&A]
My example is this

```
    SubscriptionCreateRequest:
      type: object
      required:
        - assetId
        - commitmentAmount
      properties:
        counterpartyId:
          type: string
          format: uuid
          example: "456e7890-e89b-12d3-a456-426614174001"
        assetId:
          type: string
          format: uuid
          example: "789a1234-e89b-12d3-a456-426614174002"
        commitmentAmount:
          type: number
          example: 1000000.00
      example:
        counterpartyId: "456e7890-e89b-12d3-a456-426614174001"
        assetId: "789a1234-e89b-12d3-a456-426614174002"
        commitmentAmount: 1000000.00
```

When surely the examples should be passed "up"

eg
```
  SubscriptionCreateRequest:
      type: object
      required:
        - assetId
        - commitmentAmount
      properties:
        counterpartyId:
          type: string
          format: uuid
          example: "456e7890-e89b-12d3-a456-426614174001"
        assetId:
          type: string
          format: uuid
          example: "789a1234-e89b-12d3-a456-426614174002"
        commitmentAmount:
          type: number
          example: 1000000.00
```

or 

```
    SubscriptionCreateRequest:
      type: object
      required:
        - assetId
        - commitmentAmount
      properties:
        counterpartyId:
          type: string
          format: uuid
        assetId:
          type: string
          format: uuid
        commitmentAmount:
          type: number
      example:
        counterpartyId: "456e7890-e89b-12d3-a456-426614174001"
        assetId: "789a1234-e89b-12d3-a456-426614174002"
        commitmentAmount: 1000000.00
```

In essence, it's for laziness - and less to maintain.
