### DISCUSSION TITLE
Trouble getting output from github action

### DISCUSSION THREAD

**Discussion by thom-nic** [daveshanley/vacuum#664] [Q&A]
My github workflow looks like this:
```yaml
name: Test
on:
  push:
    branches:
      - develop
      - branch/*
  pull_request:
     types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

env:
  NPM_CONFIG_UPDATE_NOTIFIER: false

jobs:
  lint-openapi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pb33f/vacuum-action@v2
      with:
        openapi_path: 'api/swagger.yml'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        print_logs: true
        show_rules: true
        fail_on_error: true
```

However I'm not seeing the expected output in the action log, and it's also failing to update the PR status:
```

3s
Run pb33f/vacuum-action@v2
  with:
    openapi_path: api/swagger.yml
    github_token: ***
    print_logs: true
    show_rules: true
    fail_on_error: true
    minimum_score: 70
  env:
    NPM_CONFIG_UPDATE_NOTIFIER: false
Run args=( lint --pipeline-output "api/swagger.yml" )
Running: docker run --rm -v /home/runner/work/asdfasf:/work:ro dshanley/vacuum lint --pipeline-output api/swagger.yml --min-score 70 --fail-severity error --show-rules
Unable to find image 'dshanley/vacuum:latest' locally
latest: Pulling from dshanley/vacuum
61320b01ae5e: Pulling fs layer
....
: Pull complete
Digest: sha256:d25ce63abb549ab92863961cd2937cac41b5ef1e42e2786fe866831e2fbce95e
Status: Downloaded newer image for dshanley/vacuum:latest
Error: failed with 1 errors
Error: Process completed with exit code 1.
Run peter-evans/create-or-update-comment@v4
  with:
    token: ***
    repository:  <removed>
    issue-number: 1820
    edit-mode: replace
    append-separator: newline
    reactions-edit-mode: append
  env:
    NPM_CONFIG_UPDATE_NOTIFIER: false
Error: Missing comment 'body' or 'body-path'.
```

Just to sanity check, I can copy the command args and run it locally `vacuum lint --pipeline-output "api/swagger.yml"`
