### ISSUE TITLE
Non-operation fields under paths treated as operations

### ISSUE THREAD

**Issue by scop** [daveshanley/vacuum#137]
In a 3.0.3 spec, for a structure like:
```yaml
paths:
  /some/path/{foo}:
    parameters:
      # ...
    get:
      # ...
    post:
      # ...
```
...it appears that `parameters` is treated as if it was an operation. I'm seeing for example the following warnings:
```
(77:5)        | warning  | Tags for `parameters` operation at path `/items/{type}/{id}` are missing     | $.paths./items/{type}/{id}.parameters
(78:7)        | warning  | Operation `parameters` at path `/items/{type}/{id}` is missing a description | $.paths./items/{type}/{id}.parameters
```

I haven't checked if this happens for other non-operation fields below a path besides `parameters`, but maybe there is a type check missing from somewhere before applying operation checks on them. https://github.com/OAI/OpenAPI-Specification/blob/3.0.3/versions/3.0.3.md#fixed-fields-7
