### ISSUE TITLE
False unused/orphaned positive for basic and session auth

### ISSUE THREAD

**Issue by scop** [daveshanley/vacuum#154]
For a swagger 2.0 spec:

```yaml
securityDefinitions:
  basicAuth:
    type: basic
  sessionAuth:
    type: apiKey
    in: header
    name: X-API-Key

security:
  - basicAuth: []
  - sessionAuth: []
```
...current vacuum warns the false positives:
```
`#/securityDefinitions/basicAuth` is potentially unused or has been orphaned
`#/securityDefinitions/sessionAuth` is potentially unused or has been orphaned
```
