### ISSUE TITLE
Runtime error when creating html-report on yaml with external-file-referenced parameter component

### ISSUE THREAD

**Issue by kimseungbin** [daveshanley/vacuum#231]
When trying to use `vacuum html-report` on a file with $ref to external file, vacuum throws runtime error below.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x100402be0]

goroutine 68 [running]:
github.com/daveshanley/vacuum/functions/openapi.OperationParameters.RunRule({}, {0x1400078bba0?, 0x8?, 0x14000056480?}, {0x14000a48a50, 0x1400016a8f0, {0x1009dbba0, 0x100a9b2a8}, {0x0, 0x0}, ...})
        /home/runner/work/vacuum/vacuum/functions/openapi/operation_parameters.go:73 +0xa00
github.com/daveshanley/vacuum/motor.buildResults({0x1400016a8f0, 0x14000428e60, {0x100a9f188, 0x14000472920}, 0x14000474168, 0x1400045cca0, 0x140008fec48, 0x140003fcc00, 0x14000428f00, 0x0, ...}, ...)
        /home/runner/work/vacuum/vacuum/motor/rule_applicator.go:405 +0x568
github.com/daveshanley/vacuum/motor.runRule({0x1400016a8f0, 0x14000428e60, {0x100a9f188, 0x14000472920}, 0x14000474168, 0x1400045cca0, 0x140008fec48, 0x140003fcc00, 0x14000428f00, 0x0, ...})
        /home/runner/work/vacuum/vacuum/motor/rule_applicator.go:330 +0x378
created by github.com/daveshanley/vacuum/motor.ApplyRulesToRuleSet
        /home/runner/work/vacuum/vacuum/motor/rule_applicator.go:165 +0x628
```

My OpenAPI structure is like this

```YAML
# openapi.yaml
# ...
paths:
  /foo:
    get:
      parameters:
        - $ref: "./bar.yaml"
```

```YAML
# bar.yaml

in: query
name: bar
schema:
  type: string
description: ...
allowEmptyValue: true
```

It was OK when I separated schema components from the main file, but it started to crash right after separating parameters component.
