### ISSUE TITLE
unknown escape character

### ISSUE THREAD

**Issue by dxps** [daveshanley/vacuum#246]
Dear all,

First of all, thanks for creating and sharing this nice tool! :pray: 

Just started playing with it and it seems very promising, not just speedy. 

However, just testing a Spectral rule (that is presented [here](https://ikenna.co.uk/2022/07/02/spectral-rule-paths-must-be-in-kebab-case/)) included in such a ruleset:
```yaml
extends: [[spectral:oas, recommended]]

rules:
  must-use-paths-kebab-case:
    description: MUST use lowercase and separate words with hyphens for path segments (kebab-case).
    message: "{{description}}"
    formats: [oas3]
    type: style
    severity: error
    given: $.paths[*]~
    then:
      function: pattern
      functionOptions:
        match: "^(\/|[a-z0-9-.]+|{[a-zA-Z0-9]+})+$"
```

And trying to use it:
- using `vacuum lint -d path/to/openapi.yaml -r path/to/ruleset.yaml`
- it throws `Unable to parse ruleset file: yaml: line 14: found unknown escape character`.

<br/>

Testing this `^(\/|[a-z0-9-.]+|{[a-zA-Z0-9]+})+$` regular expression in [regex101.com](https://regex101.com/) it looks fine.

Now, if it is declared in that `match` element without the double quotes, like this:
```yaml
        match: ^(\/|[a-z0-9-.]+|{[a-zA-Z0-9]+})+$
```
it seems that vacuum (and linting as well) works fine.

However, in _Adding Rules_ section of [Custom Ruleset](https://quobix.com/vacuum/rulesets/custom-rulesets/) page, there is an example with these quotes.

Is it ok to continue defining the `match` without the double quotes :grey_question: 

Thanks!
