### ISSUE TITLE
compatibility spectral

### ISSUE THREAD

**Issue by kervoaz** [daveshanley/vacuum#247]
Hello,
I try to use some rules copied from [spectral ](https://github.com/adidas/api-guidelines/blob/master/.spectral.yml)
Several rules are working with spectral but have issue with vacuum.
By instance:
```
  adidas-oas3-request-support-json:
    description: Every request MUST support `application/json` media type
    formats:
      - oas3
    recommended: true
    severity: error
    message: "{{description}}: {{error}}"
    given: $.paths.[*].requestBody.content[?(@property.indexOf('json') === -1)]^
    then:
      function: falsy
```
With spectral it is OK:
<img width="905" alt="image" src="https://user-images.githubusercontent.com/5457410/223696769-c0afcc24-4370-46ae-96b1-09659d88bd3b.png">

with vacuum, I have the following issue:
<img width="376" alt="image" src="https://user-images.githubusercontent.com/5457410/223697000-35fd2a82-b96b-4d9c-aa2a-5060e56d844e.png">

I have tried with quote but no solution. 
Could you help me?

thanks
