### ISSUE TITLE
Output 'true' node path in report

### ISSUE THREAD

**Issue by obfu5c8** [daveshanley/vacuum#269]
Given a custom rule such as 
```yml
 common-responses-server-error:
  description: "Missing 500 response"
  severity: error
  category:
    id: operations
  given: $.paths.*.*
  then:
    field: responses.500
    function: truthy
```

When the report is output to the terminal, each infraction is listed correctly, however the `path` shown in the output is just the verbatim `given` from the rule - this makes it difficult to quickly grok which operation is the issue.
```sh
Line / Column | Severity | Message                                           | Path
(23:7)        | error    | Missing 500 response: `responses.500` must be set | $.paths.*.*
(34:7)        | error    | Missing 500 response: `responses.500` must be set | $.paths.*.*
(45:7)        | error    | Missing 500 response: `responses.500` must be set | $.paths.*.*
(56:7)        | error    | Missing 500 response: `responses.500` must be set | $.paths.*.*
(78:7)        | error    | Missing 500 response: `responses.500` must be set | $.paths.*.*
(100:7)       | error    | Missing 500 response: `responses.500` must be set | $.paths.*.*
```

Is it possible to have the output show the 'true' path to the offending node? (e.g. `$.paths./foo.get` instead of `$.paths.*.*`)
