### ISSUE TITLE
Ruleset parse errors

### ISSUE THREAD

**Issue by nmoreaud** [daveshanley/vacuum#277]
Hello,

I would be interested in a faster alternative to spectral.
If I understand well, vacuum has been written with intent of being compatible with spectral ruleset files.
This one cannot be parsed by vacuum:

```yaml
extends: [https://raw.githubusercontent.com/baloise-incubator/spectral-ruleset/1.1.2/zalando.yml, spectral:oas]
rules:
  oas2-api-host: false
  operation-description: false
  oas2-valid-schema-example: false

  must-define-a-format-for-integer-types: false
  must-define-a-format-for-number-types: false
  must-have-info-x-api-id: false
  must-provide-api-audience: false
  must-have-info-contact-email: false
  must-have-info-contact-name: false
  must-have-info-contact-url: false
  should-prefer-standard-media-type-names: false

  must-specify-default-response: false
  must-use-problem-json-for-errors: false
  must-use-problem-json-as-default-response: false
  must-always-return-json-objects-as-top-level-data-structures: false
  should-declare-enum-values-using-upper-snake-case-format: false
  should-use-x-extensible-enum: false
  must-have-info-description: false

  ### OVERRIDES
  # override: allow actions in path, starting with "_"
  must-use-lowercase-with-hypens-for-path-segements: false
  must-use-kebabcase-for-paths-segements:
    description: Paths must be in kebab-case.
    message: '{{description}} (lower case and separated with hyphens)'
    formats: [oas3]
    type: style
    severity: error
    given: $.paths[*]~
    then:
      function: pattern
      functionOptions:
        match: "^(\/_?|([a-z0-9-.]+)|{[a-zA-Z0-9-_]+})+$"

  # override: allow root / (basic healthcheck)
  must-use-normalized-paths-without-trailing-slash:
    message: Path with trailing slash is not allowed
    description: MUST use normalized paths without empty path segments and trailing slashes [136]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#136
    severity: error
    given: $.paths.*~
    then:
      function: pattern
      functionOptions:
        notMatch: .+/$

  must-use-snake-case-for-required-property-names:
    message: Property name has to be ASCII snake_case
    description: MUST property names must be ASCII snake_case [118]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#118
    severity: error
    given: $.paths.*.*[responses,requestBody]..content..schema..required.*
    then:
      function: pattern
      functionOptions:
        match: ^[a-z_][a-z_0-9]*$

  should-use-snakecase-for-paths-variables:
    description: Paths variables should be snake_case.
    message: '{{description}}'
    severity: warn
    given: $.paths[*]~
    then:
      function: pattern
      functionOptions:
        match: "^([^{]*({[a-z0-9_]+})*)*$"

  should-use-snake-case-for-path-parameters:
    message: Path parameters should be snake_case
    description: Should use snake_case for path parameters
    severity: warn
    given: $.paths.*.parameters[?(@ && @.in=='path')].name
    then:
      function: pattern
      functionOptions:
        match: ^[a-z][_a-z0-9]*$
```
