### ISSUE TITLE
How about adding warnings for json schema keywords that do not apply to the type in the current schema?

### ISSUE THREAD

**Issue by spacether** [daveshanley/vacuum#289]
How about adding warnings for json schema keywords that do not apply to the type in the current schema?
For example if I have this schema
```
    FooInfo:
      description: Foo information
      type: object
      properties:
        name:
          description: Name of Foo
          type: string
        size:
          description: Size in bytes of the file
          type: string
          maximum: 100
          minimum: 25
        other:
          description: The type of file as determined by location
          type: string
      required: 
        - name
        - size
```
FooInfo['size'] is type string and maximum and minimum are numeric constraints. The user probably meant maxLength and minLength. Warnings for non-applicable keywords in specifically typed cases like this would help.
