### ISSUE TITLE
Discrepancy in application of custom ruleset

### ISSUE THREAD

**Issue by AdrianMachado** [daveshanley/vacuum#303]
## Issue
I am using both Spectral and Vacuum to produce issue reports on a given OpenAPI file. I tried creating a custom ruleset to verify that the `security` property is set. The rule I crafted works in Spectral but does not work in Vacuum for some reason. The spec I tested against did not have a `security` property defined

## Rule
```yaml
apimatic-security-defined:
    description: "Apimatic: In order to protect itself from outside cyberattacks, an API should define an authentication scheme and should authenticate endpoint requests made by end users. For OpenAPI specification, it is recommended to define at least one authentication scheme globally using the securitySchemes property in the components section and use it globally to authenticate all the endpoints or use it for specific endpoints."
    given: "$"
    severity: error
    then:
      - field: "security"
        function: truthy
```

## Vacuum Result
Not detected

## Spectral Result

```json
{
  code: 'apimatic-security-defined',
  message: 'Apimatic: In order to protect itself from outside cyberattacks, an API should define an authentication scheme and should authenticate endpoint requests made by end users. For OpenAPI specification, it is recommended to define at least one authentication scheme globally using the securitySchemes property in the components section and use it globally to authenticate all the endpoints or use it for specific endpoints.',
  path: [],
  severity: 0,
  source: 'example-specs/petstore.json',
  range: {
    start: { line: 0, character: 0 },
    end: { line: 790, character: 1 }
  }
}
```
