### ISSUE TITLE
Custom Rule Message

### ISSUE THREAD

**Issue by ntotten** [daveshanley/vacuum#318]
It would be nice to customize the message that is output by a rule on failure. I think this mainly applies on schema validation, but applies to many scenarios.

An example is validating that a custom extension has an array property that contains a specific element.

```yaml
  must-have-specific-thing:
    description: Must have a specific thing
    given: "$.paths[*]['get','put','post','delete','options','head','patch','trace'].x-custom-thing"
    severity: error
    then:
      field: "foo"
      function: "schema"
      functionOptions:
        schema:
          type: "array"
          allOf: 
            contains:
              - const: "my-thing"
          items:
            type: "string"
```

The fragment of the OpenAPI spec looks like this.

```json
{
      "get": {
        "summary": "Gets something",
        "x-custom-thing": {
          "foo": []
        },
}
```

When running this rule, the message output in the CLI is shown below.

```
# Validation Issues

Line / Column | Severity | Message                                                                         | Rule                               | Path
(555:18)      | error    | Must have a specific thing: valid must be >= 1, but got 0                       | must-have-specific-thing           | $.paths[*]['get','put','post','delete','options','head','pat...
```

Rather than the message `Must have a specific thing: valid must be >= 1, but got 0` i think it would be more helpful to customize the message to something like:

`Must have a specific thing: x-custom-thing.foo is missing a required value`
