### ISSUE TITLE
oasComponentDescriptions not working in 0.3.1

### ISSUE THREAD

**Issue by nkrus** [daveshanley/vacuum#324]
Hello, it looks like built-in OpenAPI function `oasComponentDescriptions` not working, because it's missed in here:
https://github.com/daveshanley/vacuum/blob/bfab25ce299b90246cf453107a42b2e9bd47075c/functions/functions.go#L80

I try to use default rule from ruleset against spec with `components.schemas` missing descriptions:
```yaml
rules:
  component-description:
    category:
      description: Documentation is really important, in OpenAPI, just about everything can and should have a description. This set of rules checks for absent descriptions, poor quality descriptions (copy/paste), or short descriptions.
      id: descriptions
      name: Descriptions
    description: Component description check
    formats:
      - oas3
      - oas3_1
    given: $
    howToFix: Components are the inputs and outputs of a specification. A user needs to be able to understand each component and what id does. Descriptions are critical to understanding components. Add a description!
    id: component-description
    recommended: true
    resolved: true
    severity: warn
    then:
      function: oasComponentDescriptions
    type: validation

```
And no reaction in final reports. 

Vacuum version = 0.3.1
