### ISSUE TITLE
Pre-commit failing with files under dir and --base dir set

### ISSUE THREAD

**Issue by guglie** [daveshanley/vacuum#327]
First of all, thanks for the great tool! 🚀

If I have my openAPI spec files in a folder named `docs` ( containing relative refs) and run the following pre-commit (while committing multiple spec files under the docs folder):

```
- repo: https://github.com/daveshanley/vacuum
  rev: "v0.3.3"
  hooks:
    -   id: vacuum
        name: Check OpenAPI doc
        files: ^docs/.*.yml$
        args: ["--base", "./docs", "--details", "--errors"]
```

It can't find the files while committing.
```
  ERROR   Please supply an OpenAPI specification to lint
```

But running it manually is ok and finds the relative refs without problems.
`pre-commit run vacuum --files docs/*.yml`
