### ISSUE TITLE
"Slice bounds out of range" error when using JS function

### ISSUE THREAD

**Issue by AdrianMachado** [daveshanley/vacuum#418]
## Problem

Vacuum will randomly error every 4-5 executions when i use custom JS functions.

```
 vacuum spectral-report -r /Users/adrianmachado/Code/rate-my-openapi-cli/rulesets/rules.vacuum.yaml  example-specs/asana.json -f /Users/adrianmachado/Code/rate-my-openapi-cli/rulesets/functions


██╗   ██╗ █████╗  ██████╗██╗   ██╗██╗   ██╗███╗   ███╗
██║   ██║██╔══██╗██╔════╝██║   ██║██║   ██║████╗ ████║
██║   ██║███████║██║     ██║   ██║██║   ██║██╔████╔██║
╚██╗ ██╔╝██╔══██║██║     ██║   ██║██║   ██║██║╚██╔╝██║
 ╚████╔╝ ██║  ██║╚██████╗╚██████╔╝╚██████╔╝██║ ╚═╝ ██║
  ╚═══╝  ╚═╝  ╚═╝ ╚═════╝ ╚═════╝  ╚═════╝ ╚═╝     ╚═╝


version: 0.7.2 | compiled: Sat, 13 Jan 2024 16:32:58 UTC
🔗 https://quobix.com/vacuum | https://github.com/daveshanley/vacuum


 INFO  Located custom javascript function: 'checkUniqueTags'
 INFO  Located custom javascript function: 'validateContentMimeType'
 INFO  Loaded 2 custom function(s) successfully.
 INFO  Linting against 85 rules: https://quobix.com/vacuum/rulesets/all
giving up finding nodes
giving up finding nodes
giving up finding nodes
panic: runtime error: index out of range [14] with length 14 [recovered]
        panic: runtime error: index out of range [14] with length 14 [recovered]
        panic: runtime error: index out of range [14] with length 14 [recovered]
        panic: runtime error: index out of range [14] with length 14

goroutine 80679 [running]:
github.com/dop251/goja.(*Runtime).runWrapped.func1()
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20231027120936-b396bb4c349d/runtime.go:2442 +0x168
panic({0x10150c980?, 0x1400522d3f8?})
        /opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:914 +0x218
github.com/dop251/goja.(*vm).handleThrow(0x1400052a900, {0x10150c980, 0x1400522d3f8})
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20231027120936-b396bb4c349d/vm.go:788 +0x3e0
github.com/dop251/goja.(*vm).try.func1()
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20231027120936-b396bb4c349d/vm.go:807 +0x48
panic({0x10150c980?, 0x1400522d3f8?})
        /opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:914 +0x218
github.com/dop251/goja.(*vm).handleThrow(0x1400052a900, {0x10150c980, 0x1400522d3f8})
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20231027120936-b396bb4c349d/vm.go:788 +0x3e0
github.com/dop251/goja.(*vm).runTryInner.func1()
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20231027120936-b396bb4c349d/vm.go:830 +0x48
panic({0x10150c980?, 0x1400522d3f8?})
        /opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:914 +0x218
github.com/dop251/goja.(*vm).initStack(...)
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20231027120936-b396bb4c349d/vm.go:1090
github.com/dop251/goja.initStackP.exec(...)
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20231027120936-b396bb4c349d/vm.go:1136
github.com/dop251/goja.(*vm).run(0x1400052a900)
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20231027120936-b396bb4c349d/vm.go:582 +0x6c
github.com/dop251/goja.(*vm).runTryInner(0x1400052a900?)
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20231027120936-b396bb4c349d/vm.go:834 +0x58
github.com/dop251/goja.(*baseJsFuncObject).__call(0x1400052ce40, {0x1400dfd41a0?, 0x1, 0x1400042fec0?}, {0x0?, 0x0}, {0x101615100?, 0x1021f32e0?})
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20231027120936-b396bb4c349d/func.go:426 +0x5e8
github.com/dop251/goja.(*baseJsFuncObject)._call(...)
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20231027120936-b396bb4c349d/func.go:442
github.com/dop251/goja.(*baseJsFuncObject).call(0x140142fbfc0?, {{0x101615100, 0x1021f32e0}, {0x1400dfd41a0, 0x1, 0x1}}, {0x0?, 0x0?})
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20231027120936-b396bb4c349d/func.go:450 +0x74
github.com/dop251/goja.(*baseJsFuncObject).Call(...)
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20231027120936-b396bb4c349d/func.go:382
github.com/dop251/goja.AssertFunction.func1.1()
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20231027120936-b396bb4c349d/runtime.go:2402 +0x6c
github.com/dop251/goja.(*vm).try(0x1400052a900, 0x14004ab57d8)
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20231027120936-b396bb4c349d/vm.go:811 +0x1e0
github.com/dop251/goja.(*Runtime).runWrapped(0x140001d5800, 0x1026fa1d8?)
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20231027120936-b396bb4c349d/runtime.go:2446 +0x64
github.com/dop251/goja.AssertFunction.func1({0x101615100?, 0x1021f32e0?}, {0x1400dfd41a0?, 0x0?, 0x0?})
        /home/runner/go/pkg/mod/github.com/dop251/goja@v0.0.0-20231027120936-b396bb4c349d/runtime.go:2401 +0x78
github.com/daveshanley/vacuum/plugin/javascript.(*JSRuleFunction).RunRule(0x140003a4b00, {0x14005577b98, 0x1, 0x14000587380?}, {0x14011af7d10, 0x14000587380, {0x1013a9d00, 0x140003c3950}, {0x0, 0x0}, ...})
        /home/runner/work/vacuum/vacuum/plugin/javascript/js_plugin.go:166 +0x284
github.com/daveshanley/vacuum/motor.buildResults({0x14000587380, 0x14000692000, 0x1400012c000, {0x101602fe8, 0x140005c36c0}, 0x1400038fc80, 0x14007224348, 0x140002ecf00, 0x14000694000, 0x1400042ebd0, ...}, ...)
        /home/runner/work/vacuum/vacuum/motor/rule_applicator.go:770 +0x588
github.com/daveshanley/vacuum/motor.runRule({0x14000587380, 0x14000692000, 0x1400012c000, {0x101602fe8, 0x140005c36c0}, 0x1400038fc80, 0x14007224348, 0x140002ecf00, 0x14000694000, 0x1400042ebd0, ...}, ...)
        /home/runner/work/vacuum/vacuum/motor/rule_applicator.go:692 +0x5dc
created by github.com/daveshanley/vacuum/motor.ApplyRulesToRuleSet.func7 in goroutine 80678
        /home/runner/work/vacuum/vacuum/motor/rule_applicator.go:553 +0x21c
```

## Repro

Here are my two functions
```javascript
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function runRule(input) {
  // Input is an array of tags
  const nameSet = new Set();
  for (const tag of input) {
    if (nameSet.has(tag.name)) {
      // eslint-disable-next-line no-undef
      const rule = context.rule.id;
      if (rule === undefined || typeof rule !== "string") {
        throw new Error("Rule is undefined");
      }
      return [
        {
          message: "Duplicate tag found: " + tag.name,
        },
      ];
    }
    nameSet.add(tag.name);
  }
}
```

and 

```javascript
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function runRule(input) {
  // Input is <mimeType, Media Type Object>
  const getErrorMessage = (mimeType) => {
    // eslint-disable-next-line no-undef
    const rule = context.rule.id;
    if (rule === undefined || typeof rule !== "string") {
      throw new Error("Rule is undefined");
    }
    if (rule.includes("request")) {
      return "Request body content type is not a valid mime type: " + mimeType;
    }
    if (rule.includes("response")) {
      return "Response body content type is not a valid mime type: " + mimeType;
    }
    return "Invalid mime type: " + mimeType;
  };
  // Input is an array of string that might be mime types
  const validPrefixes = [
    "application/",
    "audio/",
    "font/",
    "image/",
    "message/",
    "model/",
    "multipart/",
    "text/",
    "video/",
  ];
  const disallowedChars = ["!", "#", "$", "&", "_"];
  const mimeTypeRegex = /\w+\/[-+.\w]+/g;
  const mimeTypes = Object.keys(input);
  if (mimeTypes.length === 0) {
    return;
  }

  for (const mimeType of mimeTypes) {
    const hasValidPrefix = validPrefixes.some((prefix) =>
      mimeType.startsWith(prefix),
    );
    if (!hasValidPrefix) {
      return [
        {
          message: getErrorMessage(mimeType),
        },
      ];
    }
    // Ex. text/plain; charset=utf-8 -> text/plain
    const mimeTypeNoCharset = mimeType.split(";")[0];
    const hasDisallowedChars = disallowedChars.some((char) =>
      mimeTypeNoCharset.includes(char),
    );
    if (hasDisallowedChars) {
      return [
        {
          message: getErrorMessage(mimeType),
        },
      ];
    }
    const matches = mimeTypeRegex.test(mimeTypeNoCharset);
    if (!matches) {
      return [
        {
          message: getErrorMessage(mimeType),
        },
      ];
    }
  }
}
```

Here is my abridged ruleset
```yaml
extends: [[spectral:oas, all], [vacuum:owasp, all]]
  rules:
    speakeasy-duplicate-tag:
      message: "Duplicate tags detected"
      description: "Tag names must be unique. See https://www.speakeasyapi.dev/docs/openapi/validation"
      severity: warn
      given: "$.tags"
      then:
        function: "checkUniqueTags"
    speakeasy-validate-requests:
      message: "Request body content type is not a valid mime type"
      description: "Request body content type must be a valid mime type. See https://www.speakeasyapi.dev/docs/openapi/validation"
      severity: warn
      given: "$.paths..requestBody.content"
      then:
        function: "validateContentMimeType"
    speakeasy-validate-responses:
      message: "Response content type is not a valid mime type"
      description: "Responses content type must be a valid mime type. See https://www.speakeasyapi.dev/docs/openapi/validation"
      severity: warn
      given: "$.paths..responses..content"
      then:
        function: "validateContentMimeType"
```
