### ISSUE TITLE
Custom rule using Schema does not work

### ISSUE THREAD

**Issue by AdrianMachado** [daveshanley/vacuum#437]
## Summary

I tried a rule on Spectral and ported it over to Vacuum. The rule worked on Spectral but does not work on Vacuum

```yaml
apimatic-security-defined:
    description: "whatever"
    message: "'security' must be defined and not empty"
    given: "$"
    severity: warn
    then:
      field: "security"
      function: schema
      functionOptions:
        schema:
          type: array
          items:
            type: object
          minItems: 1
```

## Repro

Use any OpenAPI file without `security` defined

## Expected Result (Spectral's)

```json
{
      "code": "apimatic-security-defined",
      "message": "'security' must be defined and not empty",
      "path": [
        "security"
      ],
      "severity": 1,
      "source": "example-specs/asana.json",
      "range": {
        "start": {
          "line": 0,
          "character": 0
        },
        "end": {
          "line": 16640,
          "character": 1
        }
      }
    }
```

## Actual Result

Vacuum does not detect the issue

**Comment by daveshanley** [comment]
Hi, So after looking at this in more depth, there are a couple of issues. 

1. vaccum isn't a clone of spectral, so it does not behave 1-1 with all the same mechanisms. In this case, there are no nodes in which to check a schema against if there is no `security` node in the document. 

For example:

The following spec will pass the rule you have defined: 

```yaml
openapi: 3.1
info:
  title: "sample"
  version: "0.0.1"
paths:
 /none:
     get:
        operationId: "none"
```

The `security` field is empty, the `schema` function needs something to check against to validate it, there is no field to operate against, so it ignores it. 

2. The function you really need here is `truthy` and not `schema` (https://quobix.com/vacuum/functions/core/truthy/)

```yaml
rules:
  apimatic-security-defined:
    description: "whatever"
    message: "'security' must be defined and not empty"
    given: "$"
    severity: warn
    then:
      field: "security"
      function: truthy
```
The following specs will fail against this rule

```yaml
openapi: 3.1
info:
  title: "sample"
  version: "0.0.1"
paths:
 /none:
     get:
        operationId: "none"
``` 

And

```yaml
openapi: 3.1
info:
  title: "sample"
  version: "0.0.1"
security:
paths:
 /none:
     get:
        operationId: "none"
```
