### ISSUE TITLE
Enumeration function segfaults with more than 2 entities in list

### ISSUE THREAD

**Issue by apexkode** [daveshanley/vacuum#495]
Hi there, first of all thank you for creating this tool its super useful. 
I was testing out a few of the functions to see if they could help me with validating some YAML config with some rulesets, when I discovered an issue with the enumeration function.

Given a rule like this:
```
rules:
  example-enumeration:
    description: "Check the required values exist"
    type: style
    recommended: true
    given: $.data[*].name
    severity: error
    then:
      function: "enumeration"
      functionOptions:
        values: "must, be"
```

and a file like this:

```
data:
  - name: must
    config:
      some: value
  - name: be
    config:
      some: value
  - name: one
    config:
      some: value
```

I get the following (expected) output:

```
 vacuum lint -k -d -q -r rules/example_enumeration.yaml config/example.yaml 
version: 0.9.16 | compiled: Thu, 09 May 2024 19:57:46 UTC

INFO: Linting file 'config/example.yaml' against 1 rules: 



/home/apex/scratch/vacuum/config/example.yaml
-----------------------------------------------
Location                 | Severity | Message                                                                 | Rule                | Category   | Path
config/example.yaml:8:11 | error    | Check the required values exist: `one` must equal to one of: [must  be] | example-enumeration | Validation | $.data[*].name

Category   | Errors | Warnings | Info
Validation | 1      | 0        | 0

Linting file 'config/example.yaml' failed with 1 errors, 0 warnings and 0 informsError: failed with 1 errors

```

however if I add an extra item into the `functionOptions` vacuum will crash.

Same rule with one extra item in the functionOptions:
```
rules:
  example-enumeration:
    description: "Check the required values exist"
    type: style
    recommended: true
    given: $.data[*].name
    severity: error
    then:
      function: "enumeration"
      functionOptions:
        values: "must, be, one"
```

result of running:

```
vacuum lint -k -d -q -r rules/example_enumeration.yaml config/example.yaml 

version: 0.9.16 | compiled: Thu, 09 May 2024 19:57:46 UTC
🔗 https://quobix.com/vacuum | https://github.com/daveshanley/vacuum


INFO: Linting file 'config/example.yaml' against 1 rules: 



/home/apex/scratch/vacuum/config/example.yaml
-----------------------------------------------
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x11f8ce0]

goroutine 12 [running]:
github.com/daveshanley/vacuum/cmd.processResults({0xc00023e218, 0x1, 0xc000489ca8?}, {0xc000146a50, 0xb, 0xb}, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/vacuum/vacuum/cmd/lint.go:456 +0xf60
github.com/daveshanley/vacuum/cmd.lintFile({{0x7fff3e12ccb9, 0x13}, {0x0, 0x0}, 0x0, 0x1, 0x1, 0x0, 0x1, 0x0, ...})
        /home/runner/work/vacuum/vacuum/cmd/lint.go:348 +0x731
github.com/daveshanley/vacuum/cmd.GetLintCommand.func2.1(0xc000124fa0?, 0x0, {0x7fff3e12ccb9, 0x13})
        /home/runner/work/vacuum/vacuum/cmd/lint.go:218 +0x405
created by github.com/daveshanley/vacuum/cmd.GetLintCommand.func2 in goroutine 1
        /home/runner/work/vacuum/vacuum/cmd/lint.go:185 +0x188c
```
