### ISSUE TITLE
Node lookup timeout exceeded when using custom rule with pattern function

### ISSUE THREAD

**Issue by bravenut** [daveshanley/vacuum#502]
Hi,

When using the following custom rule definition:

```
  properties-camelCase:
    description: Properties should be camel case
    severity: warn
    message: "Properties should be camel case"
    given: $..properties[*]~
    then:
      function: pattern
      functionOptions:
        match: "^(@?[a-z0-9][A-Z0-9]{0,1}(ID)?)+$"
```
I'm getting the following error on validating one of my OpenAPI specs (I can't provide it here but will try to figure out a minimal example, if possible and needed):
![Screenshot from 2024-05-29 14-09-32](https://github.com/daveshanley/vacuum/assets/24920790/ede2105a-2282-4b4c-9381-345605d30d87)

The OAS is quite large, I can imagine that it takes quite some time to evaluate the rule. Is there a way to fix it, e.g. some configuration to increase the node lookup timeout?

Cheers
