### ISSUE TITLE
Inconsistent Handling of JSONPath Results in core functions versus Built-in Rules

### ISSUE THREAD

**Issue by LittleGreenYoda42** [daveshanley/vacuum#527]
There is inconsistent behavior in how the result jsonpath is handled for core functions versus built-in rules (e.g. operation-description). Built-in rules return a specific jsonpath (e.g. $.paths['/'].get), while core functions in custom rules return the jsonpath as defined in `Given`, including any * wildcards. 

Therefore, the lint result for core functions may contain wildcards, making it impossible to ignore single occurrences of a lint issue as the jsonpath from the lint result and the ignore file are compared to be the same string. Instead, all issues using the wildcard path must be ignored. This contradicts the ignore violations feature's purpose, which is to only ignore specific parts of the OpenAPI document and alert on newly introduced violations.

Below you can find an example openapi document, custom ruleset and an ignore file which should work in combination but don't.

`vacuum lint minimal.yaml -r custom-ruleset.yaml -d --ignore-file ignore-file.yaml`

openapi doc `minimal.yaml`
```
openapi: 3.0.1
info:
  title: Minimal OpenAPI Example
  version: 1.0.0
paths:
  /:
    get:
      responses:
        default:
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/Example"
          description: default response

components:
  schemas:
    Example:
      type: object
      properties:
        extraField:
          type: string
          example: "Additional Data"

```

custom ruleset `custom-ruleset.yaml`
```
description: Custom ruleset
extends: [[spectral:oas, off]]
rules:
  response-body-has-top-level-data-key:
    description: "The result body must be an object containing a key named data."
    type: validation
    given: $.paths.*.*.responses['200', '201', '202', '203', 'default'].content.*.schema.properties
    howToFix: The result body must be an object containing a key named data.
    severity: error
    then:
      field: data
      function: defined
```

ignore file `ignore-file.yaml`
```
response-body-has-top-level-data-key:
  - $.paths['/'].get.responses.default.content['application/json;charset=UTF-8'].schema.properties
```
