### ISSUE TITLE
Custom pattern matching in ruleset throws a panic

### ISSUE THREAD

**Issue by pyashish** [daveshanley/vacuum#549]
```   
 parameters-snake-case:
        id: parameters-snake-case
        description: Request and response parameters must be in snake_case
        given: $.paths[*][*].parameters[*].name
        formats:
            - oas3
            - oas3_1
            - oas2
        resolved: true
        recommended: true
        type: validation
        severity: error
        then:
            function: pattern
            functionOptions:
                match: ^[a-z]+(_[a-z]+)*$
        category:
            id: parameters
            name: Parameters
            description: Parameters are essential for API operations. This rule ensures that parameter names follow the snake_case convention.
        howToFix: Ensure all parameter names are in snake_case format, using underscores to separate words.
   ```
   
   I added the above ruleset, when I try to test it against a camelCase parameter, it breaks. the regex checks out , can you help please ? 
   
   
   This is the stack trace 
   
   ```
   

--------------------------------------------------------------
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x105b66280]

goroutine 5 [running]:
github.com/daveshanley/vacuum/cmd.processResults({0x140008b0008, 0xfe, 0x105dd0ff0?}, {0x1400014e008, 0x279, 0x279}, 0x0, 0x1, 0x0, 0x0, ...)
        /home/runner/work/vacuum/vacuum/cmd/lint.go:521 +0xc20
github.com/daveshanley/vacuum/cmd.lintFile({{0x16b04f7e6, 0x20}, {0x0, 0x0}, 0x0, 0x1, 0x0, 0x0, 0x1, 0x0, ...})
        /home/runner/work/vacuum/vacuum/cmd/lint.go:374 +0x594
github.com/daveshanley/vacuum/cmd.GetLintCommand.func2.1(0x0?, 0x0, {0x16b04f7e6, 0x20})
        /home/runner/work/vacuum/vacuum/cmd/lint.go:242 +0x2a8
created by github.com/daveshanley/vacuum/cmd.GetLintCommand.func2 in goroutine 1
        /home/runner/work/vacuum/vacuum/cmd/lint.go:207 +0x1634
        ```
