### ISSUE TITLE
Type null in OneOf

### ISSUE THREAD

**Issue by JulesClaussen** [daveshanley/vacuum#565]
Hello,

It seems that recent versions do not support the null type for OpenAPI 3.0
We have upgraded from v0.13.1 to v0.13.5, and the following blocks are failing:
```
    QuestionAnswer:
      properties:
        slug:
          type: string
        value:
          oneOf:
            - type: number
            - type: string
            - type: boolean
            - type: null # use null here because nullable true does not work with TS generation
            - type: array
              items:
                type: string
``` 

Is there a way to fix this, or to snooze this rule (we use precommit hooks)?
Thanks
