### ISSUE TITLE
Having trouble with `given` property in custom rules

### ISSUE THREAD

**Issue by TheTeaCat** [daveshanley/vacuum#581]
Hey, 

I'm having an issue creating a custom rule. Here's my boiled down `custom-rules.yaml`:

```yaml
extends: [all]
documentationUrl: https://example.com/docs
rules:
  define-magic-header:
    description: Response is missing a magic header.
    severity: error
    recommended: true
    formats: [oas2, oas3]
    given: $.paths..responses..headers
    then:
      field: "MagicHeader"
      function: defined
    howToFix: Ensure that the response includes a magic header.
```

And here's `my-openapi-spec.yaml`, which I think should be flagged by my custom rule:

```yaml
openapi: 3.0.0
info:
  title: My OpenAPI Spec
  version: v0.0.0
paths:
  /pets:
    post:
      responses:
        200:
          description: This needs my magic header
          headers:
            NotAMagicHeader:
              description: This is not the magic header
components: {}
```

But when I run:

```
vacuum spectral-report -r custom-rules.yaml my-openapi-spec.yaml spectral.json
```

The contents of `spectral.json` is simply:

```json
null
```

I've converted my appspec to JSON and tried using https://jsonpath.com/ to check the JSONPath I'm using in the `given` property is correct and it seems fine?

<img width="1496" alt="Screenshot 2024-11-15 at 17 29 49" src="https://github.com/user-attachments/assets/45bd0a54-eba0-4352-911d-5705e2b8cdee">
