### ISSUE TITLE
Enhancement ; Rules for detecting non recommended HTTP DELETE + Payload

### ISSUE THREAD

**Issue by LasneF** [daveshanley/vacuum#582]
implement a warning rules when a DELETE has a requestBody as even it it can be supported is not a recommended pattern 

could be set to INFO or Warning

**Comment by lobocv** [comment]
I have written a custom plugin rule that checks that delete operations return 204 and contain no response body. I can contribute it as a PR on Monday

**Comment by LasneF** [comment]
@lobocv  as the rules will looks similar if you have the solution for DELETE can you also push a rules for GET + payload as warning

btw here is a conversation for the rules 
https://stackoverflow.com/questions/978061/http-get-with-request-body

**Comment by lobocv** [comment]
Thanks for the bump! Sorry, this fell off my radar. I will try and get a PR up today or tomorrow. I have a few other things on my plate right now I need to prepare for.
I can definitely do that too @LasneF!

**Comment by LasneF** [comment]
🤔 interesting , by no content i was not looking for HTTP response code that is here subject to debate toward simplicity and 'preference' 

i was more thinking about the presence of the requestBody

**Comment by lobocv** [comment]
Ah I see. I misunderstood. Yes the HTTP DELETE and GET operations should not have a **request payload**. I was thinking of response payload. You can do this with the DSL easily:

```

  http-delete-no-request-body:
    id: delete-no-request-body
    description: HTTP DELETE operations should not accept a request body
    type: style
    severity: error
    given: "$.paths[*].delete"
    then:
      - field: 'requestBody'
        function: undefined

  http-get-no-request-body:
    id: delete-no-request-body
    description: HTTP GET operations should not accept a request body
    type: style
    severity: error
    given: "$.paths[*].get"
    then:
      - field: 'requestBody'
        function: undefined
```
