### ISSUE TITLE
Empty strings in paths

### ISSUE THREAD

**Issue by TheTeaCat** [daveshanley/vacuum#583]
Hey, thanks to #581 I've gotten my custom rule working.

Unfortunately I'm now facing an issue with the `path` property in the report containing empty strings.

I'm running:

```bash
vacuum spectral-report -r custom-rules.yaml my-openapi-spec.yaml spectral.json
```

And here's all the assets:

<details>
<summary>custom-rules.yaml</summary>

```yaml
extends: [all]
documentationUrl: https://example.com/docs
rules:
  define-magic-header:
    description: Response is missing a magic header.
    severity: error
    recommended: true
    formats: [oas2, oas3]
    given: $.paths..responses..headers
    then:
      field: "MagicHeader"
      function: defined
    howToFix: Ensure that the response includes a magic header.
```
</details>

<details>
<summary>my-openapi-spec.yaml</summary>

```yaml
swagger: 2.0
info:
  title: My OpenAPI Spec
  version: v0.0.0
paths:
  /pets:
    post:
      responses:
        200:
          description: This needs my magic header
          headers:
            NotAMagicHeader:
              description: This is not the magic header
components: {}
```
</details>

And then the resultant `spectral.json`:

```json
[
    {
        "code": "define-magic-header",
        "path": [
            "paths",
            "",
            "responses",
            "",
            "headers"
        ],
        "message": "Response is missing a magic header.: `MagicHeader` must be defined",
        "severity": 0,
        "range": {
            "start": {
                "line": 13,
                "character": 13
            },
            "end": {
                "line": 13,
                "character": 13
            }
        },
        "source": "my-openapi-spec.yaml"
    }
]
```
