### ISSUE TITLE
Ability to suppress rules inline

### ISSUE THREAD

**Issue by apiarya** [daveshanley/vacuum#619]
### Request: Suppress Specific Rule on a Case-by-Case Basis  

While managing a large portfolio of OpenAPI specifications, some APIs may have existed for years and belong to deprecated yet supported product lines. In these cases, only specific types of issues are addressed, while others receive exceptions to remain unchanged.  

Currently, suppression options are too broad—disabling a rule entirely or ignoring a entire openapi file is not feasible since operations are scattered across multiple locations. A more granular approach is needed to **suppress a specific issue/problem on a case-by-case basis** while maintaining overall rule enforcement.  

### Feature Request  
Support for ignoring a **specific rule on a specific file and line** would provide fine-grained control over rule enforcement. This would function similarly to Java’s `@SuppressWarnings("squid:S00112")` annotation in SonarQube, allowing targeted exceptions without disabling rules globally.  
Ref: [Turning Sonar off for certain code](https://stackoverflow.com/questions/10971968/turning-sonar-off-for-certain-code)  

#### Example Use Case  
Consider a scenario where `/delete` was used in a URL when designing a particular API operation. Over time, this API has been heavily integrated across multiple systems. According to modern design standards, this is no longer considered a best practice and violates the [no-http-verbs-in-path](https://quobix.com/vacuum/rules/operations/no-http-verbs-in-path/) rule. However, since removing or renaming this operation would be a **breaking change**, an exception is required.  

Rather than completely suppressing the rule, a better approach would be to **downgrade the severity** of the issue so it does not negatively impact the overall API score.  

#### Proposed Solution  
I wish there is an official OpenAPI notation. But for now we can imagine a vendor extension like `x-suppress-issue:` capturing rule, reason and downgraded level.
A mechanism similar to the following could be used to record and manage exceptions:  

```yaml
/bookings/{bookingId}/delete:
    x-suppress-issue:
      - ruleId: no-http-verbs-in-path
        reason: |
          This is a legacy operation that cannot be removed on this KTLO product line.
          Fixing this issue is a breaking change.
          Exception #gov6145 approved by joe@example.com on Feb, 16 2023.
        override-severity: info   
    parameters:
      - name: bookingId
        in: path
        ...
    delete:
      summary: Delete a booking
    ...
```  

### Rationale  
API design guidelines evolve over time, and custom rules are continuously introduced. As new rules are evaluated against existing API designs, most APIs can be expected to comply. However, in some cases, exceptions must be granted and documented appropriately.  

This approach encourages **[Clean As You Code](https://docs.sonarsource.com/sonarqube-server/10.3/user-guide/clean-as-you-code/)** practices without penalizing entire APIs with lower scores for retaining legacy design choices. It provides a structured way to manage exceptions transparently while maintaining governance and compliance.
