### ISSUE TITLE
Date formatted example values do not accept RFC3339 Date

### ISSUE THREAD

**Issue by nicholasss** [daveshanley/vacuum#654]
The first section below is not accepted by the linter, and appears as a warning.

Here is the CLI output:
`openapi.yaml:84:17 | warning  | invalid jsonType time.Time | oas3-valid-schema-example | Examples | $.paths['/api/v1/create-user'].post.responses['201'].content...`

Here is the HTML report:
<img width="1508" alt="vacuum html report with identical information to the cli output, expect with additional information on how to fix the issue." src="https://github.com/user-attachments/assets/4f687e2a-45ae-499b-87ea-1529047d5f37" />

```yaml
          content:
            application/json:
              schema:
                $ref: "./components/schemas/CreateUserResponse.yaml"
              examples:
                craig:
                  summary: Example of creating a user named Craig.
                  value:
                    id: 26a4983b-82cf-41ea-b447-8a4f34b271e2
                    createdAt: 2006-01-02T15:04:05Z+07:00
                    updatedAt: 2006-01-02T15:04:05Z+07:00
                    createdBy: project-frontend v0.1.0
                    updatedBy: project-frontend v0.1.0
                    joinDate: 2006-01-02
                    isAdmin: false
                    email: craig482@gmail.com

```

I am able to satisfy the linter with the following change to the joinDate value, in which it is expanded to an RFC3999 date-time.

```yaml
          content:
            application/json:
              schema:
                $ref: "./components/schemas/CreateUserResponse.yaml"
              examples:
                craig:
                  summary: Example of creating a user named Craig.
                  value:
                    id: 26a4983b-82cf-41ea-b447-8a4f34b271e2
                    createdAt: 2006-01-02T15:04:05Z+07:00
                    updatedAt: 2006-01-02T15:04:05Z+07:00
                    createdBy: project-frontend v0.1.0
                    updatedBy: project-frontend v0.1.0
                    joinDate: 2006-01-02T00:00:00Z+00:00
                    isAdmin: false
                    email: craig482@gmail.com
```

I would have thought that it would accept an RFC3999 date, as that is what the format is specified as in the [Format Registry](https://spec.openapis.org/registry/format/).

Here is the schema that it is validating against.

```yaml
type: object
properties:
  id:
    type: string
    format: uuid
  createdAt:
    type: string
    format: date-time
  updatedAt:
    type: string
    format: date-time
  createdBy:
    type: string
  updatedBy:
    type: string
  joinDate:
    type: string
    format: date
  isAdmin:
    type: boolean
  email:
    type: string
    format: email
required:
  - id
  - createdAt
  - updatedAt
  - createdBy
  - updatedBy
  - joinDate
  - isAdmin
  - email
```

TL;DR: It seems that response examples of format date are being evaluated against RFC3999 date-time formatting, and not RFC3999 date.
